library(shiny)
library(shinydashboard)
library(DT)
library(sqldf)
library(ggplot2)
library("data.table")
library(clustMixType)
library(klaR)
library(dplyr)
require(plyr)

library(rpart)
library(visTree)
library(rattle)
library(party)		
library(caret)
library(rpart.plot)	
library(partykit)
library(stringr)
library(plotly)
library(knitr)


survey_data_default <- read.csv('intellisurvey_demo.csv')
source('function.R')
