library(shiny)
library(shinydashboard)
library(DT)
library(sqldf)
library(ggplot2)
library("data.table")
library(clustMixType)
library(klaR)
library(dplyr)
require(plyr)

library(rpart)
library(visTree)
library(rattle)
library(party)		
library(caret)
library(rpart.plot)	
library(partykit)
library(stringr)
library(plotly)
library(knitr)
library(kableExtra)
library(tinytex)
library(webshot)
library(scales)
library(weights)
library(lubridate)
library(RColorBrewer)

options(stringsAsFactors = F)

source('function.R')
source('function2.R')
source('function3.R')
